@theo/emoji reaction bar
blokboy/bbydao pull request #49
Opened 2022-04-01 18:27 UTC by taayyohh

Felt like this would be a good place to make a PR since some changes effect a bunch of files and I know that can cause conflicts if left out for too long. 

**Changes:**
Reaction Bar / Button:
- desktop & mobile
- "default reactions" 
- remove reaction on click of already existing reaction
- list count of same reaction types

Todo: I'm gonna do this next
- theme styles

Considerations: @joelazarz thoughts?
- refactor `EmojiPicker` : considering whether there should just be one picker component for the whole `Messages` component that always pops up in the same place (i.e bottom right corner).
- use click away instead of close on MouseLeave to close Picker.

2022-04-01 18:59 UTC, blokboy commented on components/Messages/DesktopMessages/DesktopMessageView/DesktopMessageContent.js
> +      {messages?.sort((a, b) => (a.createdAt > b.createdAt) ? 1 : -1)?.map(message => (
i'll probably move the sort for this onto the backend so we don't have to process anymore info on client than we need to but good catch i thought this was already coming through in order of `createdAt`

2022-04-01 19:11 UTC, taayyohh commented on components/Messages/DesktopMessages/DesktopMessageView/DesktopMessageContent.js
> +      {messages?.sort((a, b) => (a.createdAt > b.createdAt) ? 1 : -1)?.map(message => (
cool will remove from here and mobile

2022-04-04 20:12 UTC, blokboy commented on components/Dao/SidePanel/FollowModal.js
>      /*
We can probably get rid of this as its confusing to have these random comments here now lol

2022-04-04 20:20 UTC, blokboy commented on components/Dao/SidePanel/MemberCard.js
>    const [{ data, error, loading }, lookupAddress] = useEnsLookup({
how is `lookupAddress` being used here? is it just a callback f(x)?

2022-04-04 20:45 UTC, blokboy commented on components/Dao/TokensNfts/SellModal.js
>    const osSellModalOpen = useOsStore(state => state.osSellModalOpen)
at line 57 just wanted to clarify why we set up the object this way for NFT sales
{
 txHash: we don't have a txHash yet because we haven't created a Gnosis Safe transaction (we don't do that until execution so this is how we categorize it off chain),
 value: how much ETH are we hoping to sell/buy/offer,
 receiver: this is just the image url of the NFT we want to buy so that we can display it in the txCard but we may need to increase size of card so that this is actually viewable by anyone over the age of 35 
}

2022-04-04 20:46 UTC, blokboy commented on components/Dao/index.js
> +        <title>{`bbyDAO | ${walletSnippet(data.safeInfo.address)}`}</title>
Is there a check in walletSnippet that handles if `data` isn't the expected addr value we want back?

2022-04-04 20:49 UTC, blokboy commented on components/Messages/CreateThreadModal/CreateThreadForm.js
> +          this thread will be created for {channelAddress?.substring(0, 6)}...
can we use `walletSnippet` here?

2022-04-04 20:50 UTC, blokboy commented on components/Messages/DesktopMessages/DesktopInboxNavigation/DesktopInboxCard.js
> +        {safe?.length > 30 ? walletSnippet(safe) : safe}
This is great but let's see if we can bring in the actual bbyDAO names now that we have that on the backend and represent those here first then fall back to `walletSnippet` when a name isn't available

2022-04-04 20:53 UTC, blokboy commented on components/Messages/DesktopMessages/DesktopMessageView/DesktopMessageContent.js
> +      refetchOnWindowFocus: true,
Why did you decide to `refetchOnWindowFocus` ? Is this for users that scroll to bottom and then return to viewport later? I'm wondering if this piece is possibly responsible for reloads on network activity happening so heavily on messages

2022-04-04 20:56 UTC, blokboy commented on components/Messages/DesktopMessages/DesktopMessageView/DesktopMessageInput.js
>        setTimeout(() => ref.current.setSelectionRange(newCursor, newCursor), 10)
I'm a bit confused as to what's happening in this last line can someone help me i'm a noob

2022-04-04 21:00 UTC, blokboy commented on components/Messages/MessageUi/Card/index.js
> +          {reactions !== null && Object.entries(reactions).reduce(function(accumulator = [], currentValue) {
we should try to optimize this call and break apart some of these chained array functions for readability. or we could add comments showing how the data is transformed between calls

2022-04-04 21:03 UTC, blokboy commented on components/Messages/MessageUi/Card/index.js
> +    const alreadyExists = reactions?.[accountData?.address]?.id === emoji.id
not really a big deal but i don't think we even need to compare to `emoji.id` here bc we only allow one reaction per user per message so if they have a reaction already then we can treat this as `true` no matter which emoji they picked?

2022-04-04 21:05 UTC, blokboy commented on utils/helpers.js
> +export const walletSnippet = (addr) =>
this anwers my question above re: wallet snippet error checks -- lets just get some in there for when the addr isn't what we expect

2022-04-04 21:08 UTC, blokboy requested changes
Left single comments in the files (lemme know if this is annoying or you have another method you prefer code review)

2022-04-04 21:17 UTC, extrawaterjoe commented on components/Messages/DesktopMessages/DesktopMessageView/DesktopMessageInput.js
>        setTimeout(() => ref.current.setSelectionRange(newCursor, newCursor), 10)
this sets the emoji into the input, appending it into message state, then sets the input cursor to the space right after the emoji (some emojis are more than 1 character)

2022-04-04 21:21 UTC, extrawaterjoe commented on components/Messages/DesktopMessages/DesktopMessageView/DesktopMessageContent.js
> +      refetchOnWindowFocus: true,
this probably won't be necessary at all when we use websockets. This would help to keep things feeling realtime (if a user switches tabs then switches back and there's a new message, it'll render from that fetch) however it's definitely not an approach we want to stick with

2022-04-04 22:43 UTC, taayyohh commented on components/Messages/MessageUi/Card/index.js
> +    const alreadyExists = reactions?.[accountData?.address]?.id === emoji.id
This logic was meant for when a user clicks an emoji button that they have already reacted as, so that it would remove that reaction on click, without the comparison if I user has reacted with `heart` then clicks `heart` again the emoji would remain put i think.

2022-04-04 23:09 UTC, blokboy approved these changes

2022-04-05 01:44 UTC, 0xburden commented on components/Messages/MessageUi/Card/index.js
> +          {reactions !== null && Object.entries(reactions).reduce(function(accumulator = [], currentValue) {
ideally computed values like whatever array the reducer spits out should be extracted out of render and wrapped in a useMemo or useCallback that returns the array, we should definitely try to keep logic like this out the primary render function of all components in general imo, also helps with performance across the app under the right circumstances

2022-04-05 13:05 UTC, taayyohh commented on components/Messages/DesktopMessages/DesktopInboxNavigation/DesktopInboxCard.js
> +        {safe?.length > 30 ? walletSnippet(safe) : safe}
Updated this using the docs from the backend but wasn't able to verify my implementation since I'm not in a DAO yet (haven't set up postman info or anything yet eiether) -- but seems straightforward

2022-04-05 13:07 UTC, taayyohh reviewed
Updated walletSnippet in all the places it could be used and resolved remaining comments including stripping the emoji reduce fn from the render logic

2022-04-08 18:45 UTC, extrawaterjoe commented on components/Messages/MessageUi/Card/index.js
> +const MessageCard = ({ message }) => {
I think because the emoji picker is one of the most expensive components to load and it's loading on every message card there's a decrease in performance on /messages, especially when loading up a thread with a lot of messages.

will need to use NimblePicker if we continue with this emoji picker - [emoji-mart](https://github.com/missive/emoji-mart#datasets) -- as well as limit the number of messages initially fetched.

2022-04-08 18:47 UTC, extrawaterjoe approved these changes

2022-04-08 19:39 UTC, merged